# Generated by Django 3.2.8 on 2021-10-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Godok',
            fields=[
                ('godok_no', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('die', models.IntegerField()),
            ],
            options={
                'db_table': 'godok',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeoulCenter',
            fields=[
                ('center_no', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('district', models.CharField(max_length=255)),
                ('welfare', models.IntegerField()),
                ('citizen', models.IntegerField(blank=True, null=True)),
                ('class_field', models.IntegerField(blank=True, db_column='class', null=True)),
            ],
            options={
                'db_table': 'seoul_center',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeoulElder',
            fields=[
                ('elder_no', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('district', models.CharField(max_length=255)),
                ('silver', models.IntegerField()),
                ('lower', models.IntegerField(blank=True, null=True)),
                ('general', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seoul_elder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeoulPeople',
            fields=[
                ('people_no', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('all_people', models.IntegerField()),
                ('elder_people', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seoul_people',
                'managed': False,
            },
        ),
    ]
