# Generated by Django 3.2.8 on 2021-10-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HJ_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoulHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.CharField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(blank=True, max_length=255, null=True)),
                ('addr', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('kind', models.CharField(blank=True, max_length=255, null=True)),
                ('wk', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'seoul_hospital',
                'managed': False,
            },
        ),
    ]
