# Generated by Django 3.2.8 on 2021-11-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HJ_app', '0002_seoulhospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoulHospitalAd',
            fields=[
                ('h_no', models.AutoField(primary_key=True, serialize=False)),
                ('h_name', models.CharField(max_length=255)),
                ('h_addr', models.CharField(max_length=255)),
                ('h_tel', models.CharField(max_length=255)),
                ('h_url', models.CharField(max_length=255)),
                ('h_image', models.ImageField(upload_to='')),
                ('h_comment', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'seoul_hospital_ad',
                'managed': False,
            },
        ),
    ]
