# Generated by Django 3.2.8 on 2021-11-08 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HJ_app', '0004_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
