# Generated by Django 3.2.8 on 2021-11-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HJ_app', '0005_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
