# Generated by Django 3.2.8 on 2021-11-15 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HJ_app', '0006_imageupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUpLoad',
        ),
    ]
